name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_LOG: debug

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          #sparse-checkout: .

      - uses: taiki-e/install-action@v2
        with:
          tool: zola
      - run: zola build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: 'public'
