name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: TonySpegel/zola-build-action@v1
        #env:
        #  CONFIG_FILE: "config.live.toml"

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: 'public'
